name: 05 - version node
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: version Node
        run: node --version
      - name: instalar jsonlint
        run: sudo apt-get install jsonlint
      - name: verificar fichero .json
        run: jsonlint-php package.json
