name: 05a - Expresiones
on:
  push:
    branches: ["master"]
jobs:
  expresiones:
    runs-on: ubuntu-latest
    steps:
      - name: Operadores
        id: operadores
        run: echo "${{ 2 > 1}}"
      
      - name: Inspeccionar github
        id: githubContext
        run: echo '${{toJson(github)}}'
      
      - name: Evento y actor
        id: eventoActor
        run: | 
          echo 'Evento disparador: ${{github.event_name}}'
          echo 'Lanzado por: ${{github.actor}}'
      
      - name: Filtro de objeto
        id: stepsContext
        run: | 
          echo '${{toJson(steps)}}'
          echo '${{join(steps.*.conclusion)}}'
      
      