name: 06b - Pasar valores entre steps
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  pasar_valores:
    runs-on: ubuntu-latest
    steps:
      - name: Generar nÃºmeros aleatorios
        run: | 
          echo "random_number=$((1 + RANDOM % 10))" >> "$GITHUB_ENV"
      - name: Leer resultados
        run: | 
          echo "El valor del dado es: $random_number"